import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createVoiceCall,voiceConfig} from '../secretary-voice.js';
import worker from '../gpt-worker.js';
function fixture(){const db=new DatabaseSync(':memory:');const env={OPENAI_API_KEY:'only-server-test-key',AGENT_DB:{prepare(sql){const bind=(...args)=>({async first(){return db.prepare(sql).get(...args);},async run(){return{meta:{changes:db.prepare(sql).run(...args).changes}};}});return{...bind(),bind};}}};return{env,db};}
test('통화는 인증이 필요하고 잘못된 연결 정보는 API로 보내지 않는다',async()=>{const f=fixture();const response=await worker.fetch(new Request('https://worker.test/voice/call',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),f.env);assert.equal(response.status,401);await assert.rejects(createVoiceCall({env:f.env,uid:'a',body:{id:'one',sdp:'invalid'},fetcher:()=>{throw Error('must not call');}}),e=>e.status===400);f.db.close();});
test('서버가 음성 모델과 업무 전달 도구를 설정하고 키를 브라우저에 보내지 않는다',async()=>{const f=fixture();let requests=0;const fetcher=async(url,options)=>{requests++;assert.equal(url,'https://api.openai.com/v1/realtime/calls');assert.equal(options.headers.Authorization,'Bearer only-server-test-key');assert.match(options.headers['OpenAI-Safety-Identifier'],/^[a-f0-9]{64}$/);const config=JSON.parse(options.body.get('session'));assert.equal(config.audio.input.turn_detection.interrupt_response,true);assert.equal(config.tools.length,1);assert.equal(config.tools[0].name,'ask_secretary');return new Response('v=0\r\nanswer');};const call=()=>createVoiceCall({env:f.env,uid:'a',body:{id:'one',sdp:'v=0\r\noffer'},fetcher});const result=await call();assert.equal(result.sdp,'v=0\r\nanswer');assert.equal(JSON.stringify(result).includes(f.env.OPENAI_API_KEY),false);await assert.rejects(call(),e=>e.status===409);assert.equal(requests,1);assert.equal(f.db.prepare('SELECT status FROM office_voice_calls').get().status,'connected');f.db.close();});
test('연결 실패는 성공으로 기록하지 않고 공급자 오류의 민감한 본문은 노출하지 않는다',async()=>{const f=fixture();await assert.rejects(createVoiceCall({env:f.env,uid:'a',body:{id:'one',sdp:'v=0'},fetcher:async()=>new Response('private-provider-error',{status:403})}),e=>e.status===502&&!e.message.includes('private-provider-error'));assert.equal(f.db.prepare('SELECT status FROM office_voice_calls').get().status,'failed');f.db.close();});
test('계정별 연결 제한과 별도 모델 설정이 적용된다',async()=>{const f=fixture();f.env.SECRETARY_VOICE_MODEL='custom-voice';assert.equal(voiceConfig(f.env).model,'custom-voice');await createVoiceCall({env:f.env,uid:'a',body:{id:'one',sdp:'v=0'},fetcher:async()=>new Response('v=0')});for(let i=0;i<11;i++)f.db.prepare('INSERT INTO office_voice_calls VALUES(?,?,?,?)').run('a','call'+i,Date.now(),'connected');await assert.rejects(createVoiceCall({env:f.env,uid:'a',body:{id:'blocked',sdp:'v=0'}}),e=>e.status===429);const other=await createVoiceCall({env:f.env,uid:'b',body:{id:'one',sdp:'v=0'},fetcher:async()=>new Response('v=0')});assert.equal(other.ok,true);f.db.close();});
