'use client';
import {useState,useEffect,useCallback,useRef} from 'react';
type Target={id:string;name:string;url:string;enabled:boolean;baselineAt:number|null;lastScanAt?:number};
type Settings={actorName:string;actorUrl:string;dailyEnabled:boolean;autoLike:boolean;checkIntervalMinutes:number;maxPerRun:number};
type Post={key:string;targetId:string;targetName:string;status:string;snippet:string;url:string;dateLabel:string;note?:string};
type State={targets:Target[];removedTargets:Target[];settings:Settings;posts:Record<string,Post>;events:{at:number;message:string;level:string}[];connection:{connected:boolean};job:null|{mode:string;index:number;ids:string[];target?:string;dueAt:number;running:boolean};busy:boolean;nextRunAt:number|null;login:null|{expiresAt:number};quota:{plan:'free'|'paid';remaining:number;budget:number|null;used:number;resetsAt:number;month:string;monthUsed:number;monthBudgetHours:number;estimatedUsd:number;planCheckedAt:number|null}};
const date=(v:number|null|undefined)=>v?new Date(v).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Seoul'}):'아직 없음';
const labels:Record<string,string>={new:'새 글',baseline:'첫 기준',old:'이전 글',review:'직접 확인',done:'좋아요 완료',already:'기존 반응',skipped:'제외',attempting:'처리 중',uncertain:'결과 확인 필요'};
async function command(message:Record<string,unknown>){const r=await fetch('/api/command',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(message)});const v=await r.json() as {ok:boolean;error?:string;result:any};if(!v.ok)throw new Error(v.error||'요청을 처리하지 못했습니다.');return v.result;}
export default function Dashboard(){
  const [state,setState]=useState<State|null>(null),[settings,setSettings]=useState<Settings|null>(null),[pending,setPending]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(false),[query,setQuery]=useState(''),[name,setName]=useState(''),[url,setUrl]=useState(''),[filter,setFilter]=useState('new'),[selected,setSelected]=useState<string[]>([]),[remove,setRemove]=useState<Target|null>(null),[loginUrl,setLoginUrl]=useState(''),[consent,setConsent]=useState(false);
  const dirty=useRef(false);
  const refresh=useCallback(async()=>{const s=await command({type:'get'});setState(s);if(!dirty.current)setSettings(s.settings);},[]);
  useEffect(()=>{let live=true;const load=()=>refresh().catch(e=>{if(live){setNotice(e.message);setError(true);}});load();const t=setInterval(load,15000);return()=>{live=false;clearInterval(t);};},[refresh]);
  const act=async(message:Record<string,unknown>,success?:string)=>{setPending(true);setNotice('');try{const result=await command(message);await refresh();setError(false);if(success)setNotice(success);return result;}catch(e){setError(true);setNotice(e instanceof Error?e.message:'처리하지 못했습니다.');return null;}finally{setPending(false);}};
  const blocked=pending||!!state?.job||!!state?.busy||!!state?.login;
  const edit=(key:keyof Settings,value:unknown)=>{dirty.current=true;setSettings(s=>s?{...s,[key]:value}:s);};
  const posts=Object.values(state?.posts||{}).filter(p=>filter==='all'||state?.targets.some(t=>t.id===p.targetId)&&(filter==='done'?['done','already'].includes(p.status):filter==='review'?['review','uncertain'].includes(p.status):p.status===filter));
  const select=(key:string,on:boolean)=>setSelected(s=>on?[...s,key]:s.filter(k=>k!==key));
  return <main className="shell"><header className="top"><div className="brand"><span className="brand-icon" aria-hidden="true">새</span>새 글 도우미</div><span className="muted">나만의 소식 관리 공간</span></header>
  <div className="intro"><div><h1>동료의 소식, 한눈에.</h1><p className="muted">휴대폰에서도 명단과 확인 기록을 이어서 관리하세요.</p></div><span className="badge">{state?.quota.plan==='paid'?'유료 실행 연결됨':'개인용 관리 공간'} · 비공개</span></div>
  {notice&&<div role="status" className={'notice'+(error?' error':'')}>{notice}</div>}
  {!state?<section className="card"><h2>관리 공간 연결 중</h2><p className="muted" style={{margin:'14px 0'}}>저장된 명단과 실행 상태를 불러옵니다.</p><button onClick={()=>refresh().catch(e=>{setNotice(e.message);setError(true);})}>다시 확인</button></section>:<div className="grid"><div>
  <section className="card run"><div className="card-head"><h2>{state.job?(state.job.running?'동료 소식을 확인하고 있어요':'남은 동료 확인을 기다리고 있어요'):'지금 소식을 확인해 보세요'}</h2><span className="badge">{state.targets.filter(t=>t.enabled).length}명 확인 대상</span></div>
  <p>{state.job?`${state.job.ids.length}명 중 ${state.job.index}명 완료 · ${state.job.target||'순서대로 확인'}${!state.job.running?' · 다음 시작 '+date(state.job.dueAt):''}`:'처음 전체 확인을 하면 기존 글을 기준으로 저장합니다. 그다음부터 새 글을 구분합니다.'}</p>
  <div className="buttons"><button className="primary" disabled={blocked||!state.connection.connected} onClick={()=>act({type:'run',mode:'scan'},'새 글 확인을 시작합니다.')}>새 글 확인</button><button disabled={blocked||!state.connection.connected} onClick={()=>act({type:'run',mode:'auto'},'새 글 확인·좋아요를 시작합니다.')}>확인하고 좋아요</button><button disabled={pending||!state.job&&!state.settings.dailyEnabled} onClick={()=>act({type:'stop'},'자동 확인과 진행 중인 작업을 중단했습니다.')}>모두 중단</button></div>
  {state.job&&<div className="progress" aria-label="확인 진행률"><span style={{width:(state.job.index/state.job.ids.length*100)+'%'}}/></div>}</section>
  <section className="card"><div className="card-head"><h2>동료 목록<span className="count">{state.targets.length}명</span></h2></div><input className="search" aria-label="동료 이름 검색" placeholder="동료 이름 검색" value={query} onChange={e=>setQuery(e.target.value)}/>
  {state.targets.filter(t=>t.name.includes(query)).map(t=><div className="person" key={t.id}><span className="avatar">{t.name.slice(0,1)}</span><div className="person-info"><a href={t.url} target="_blank" rel="noreferrer">{t.name}</a><small>{t.enabled?'확인 대상':'일시 제외'} · {t.lastScanAt?date(t.lastScanAt):'아직 확인하지 않음'}</small></div><div className="person-actions"><button disabled={blocked||!state.connection.connected} onClick={()=>act({type:'runTargetLatest',targetId:t.id},'최신 글 1개 확인·좋아요를 시작합니다.')}>이 동료만 확인</button><button disabled={blocked} onClick={()=>act({type:'toggleTarget',id:t.id})}>{t.enabled?'일시 제외':'다시 포함'}</button><button className="danger" disabled={blocked} onClick={()=>setRemove(t)}>삭제</button></div></div>)}
  {!state.targets.filter(t=>t.name.includes(query)).length&&<p className="empty">{query?'검색한 동료가 없습니다.':'첫 동료를 등록해 보세요.'}</p>}
  <p className="muted" style={{marginTop:14}}>‘이 동료만 확인’은 최신 글 1개에 좋아요까지 누릅니다. 이미 누른 반응은 유지합니다.</p>
  <form className="add-form" onSubmit={async e=>{e.preventDefault();if(await act({type:'addTarget',name,url},'동료를 등록했습니다.')){setName('');setUrl('');}}}><input required aria-label="동료 이름" placeholder="동료 이름" value={name} maxLength={60} onChange={e=>setName(e.target.value)} disabled={blocked}/><input required type="url" aria-label="페이스북 주소" placeholder="페이스북 프로필 주소" value={url} onChange={e=>setUrl(e.target.value)} disabled={blocked}/><button className="primary" disabled={blocked}>등록</button></form>
  {!!state.removedTargets.length&&<details><summary>삭제한 동료 {state.removedTargets.length}명</summary>{state.removedTargets.map(t=><div className="restore" key={t.id}><span>{t.name}</span><button disabled={blocked} onClick={()=>act({type:'restoreTarget',id:t.id},'기존 기록과 함께 복원했습니다.')}>복원</button></div>)}</details>}</section>
  <section className="card"><div className="card-head"><h2>확인한 게시물</h2><select aria-label="게시물 상태" value={filter} onChange={e=>{setFilter(e.target.value);setSelected([]);}}><option value="new">새 글</option><option value="review">직접 확인</option><option value="done">처리 완료</option><option value="all">전체 기록</option></select></div>
  {posts.map(p=><article className="post" key={p.key}><input className="check" type="checkbox" aria-label={p.targetName+' 게시물 선택'} checked={selected.includes(p.key)} onChange={e=>select(p.key,e.target.checked)} disabled={blocked||!state.targets.some(t=>t.id===p.targetId&&t.enabled)||!['new','review'].includes(p.status)}/><div className="post-content"><div className="post-head"><strong>{p.targetName}</strong><span className="muted">{p.dateLabel}</span><span className={'status '+p.status}>{labels[p.status]||p.status}</span>{!state.targets.some(t=>t.id===p.targetId)&&<span className="status">삭제된 동료</span>}</div><p>{p.snippet||'본문 미리보기 없음'}</p>{p.note&&<small>{p.note}<br/></small>}<a href={p.url} target="_blank" rel="noreferrer">글 열기</a></div></article>)}
  {!posts.length&&<p className="empty">아직 표시할 게시물이 없어요.<br/>동료 소식을 확인하면 여기에 모입니다.</p>}
  <div className="buttons" style={{marginTop:18}}><button disabled={blocked||!selected.length||!state.connection.connected} onClick={async()=>{await act({type:'run',mode:'selected',keys:selected});setSelected([]);}}>선택한 새 글 좋아요</button><button disabled={blocked||!selected.length} onClick={async()=>{await act({type:'skip',keys:selected});setSelected([]);}}>선택한 글 제외</button></div><p className="muted" style={{marginTop:12}}>최근 확인한 300개를 표시합니다. 처리 여부는 서버에 계속 보관됩니다.</p></section>
  <section className="card"><div className="card-head"><h2>처리 기록</h2></div>{state.events.slice(0,30).map((e,i)=><div className={'log '+e.level} key={i}><time>{date(e.at)}</time>{e.message}</div>)}{!state.events.length&&<p className="empty">확인을 시작하면 기록이 남습니다.</p>}</section></div>
  <aside className="side"><section className="card"><h2>페이스북 연결</h2><div className="connection" style={{marginTop:18}}><strong>{state.connection.connected?'로그인 상태 연결됨':'로그인을 연결해 주세요'}</strong><p className="muted">서버에서 페이스북 로그인 화면을 열어 직접 로그인합니다.</p><button className="full primary" disabled={pending||!!state.job||state.busy||!!state.login} onClick={async()=>{const r=await act({type:'loginStart'});if(r?.url)setLoginUrl(r.url);}}>로그인 화면 준비</button></div>
  {state.login&&<div className="login-box">{loginUrl?<a href={loginUrl} target="_blank" rel="noreferrer">페이스북 로그인 화면 열기</a>:<p className="muted">이전에 열어 둔 로그인 화면을 완료해 주세요.</p>}<p className="muted">{date(state.login.expiresAt)}까지 완료해 주세요.</p><label className="switch"><span>PC 없이 실행하도록 로그인 상태를 서버에 보관합니다.</span><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/></label><button className="full" disabled={pending||!consent} onClick={async()=>{if(await act({type:'loginFinish'},'로그인을 연결했습니다.')){setLoginUrl('');setConsent(false);}}}>로그인 완료·연결</button></div>}
  {(state.connection.connected||state.login)&&<button className="full" disabled={pending||!!state.job} onClick={()=>act({type:'logout'},'서버 로그인 상태를 삭제했습니다.')}>연결 해제</button>}
  <div className="quota">{state.quota.plan==='paid'?<><strong>이번 달 서버 실행</strong><small>{(state.quota.monthUsed/3600000).toFixed(2)}시간 사용 · 하루 9분 제한 해제</small><div className="quota-track"><span style={{width:Math.min(100,state.quota.monthUsed/(state.quota.monthBudgetHours*3600000)*100)+'%'}}/></div><label className="field" style={{marginTop:14}}>월 실행 예산<select aria-label="월 실행 예산" value={state.quota.monthBudgetHours} disabled={pending||state.busy||!!state.login||!!state.job?.running} onChange={e=>act({type:'budget',hours:Number(e.target.value)},'월 실행 예산을 저장했습니다.')}>{[30,100,200,500].map(h=><option value={h} key={h}>{h}시간 · 기본료+브라우저 약 ${(5+Math.max(0,h-10)*0.09).toFixed(2)}</option>)}</select></label><p className="muted">현재 기본료·브라우저 예상 ${state.quota.estimatedUsd.toFixed(2)}. 로그인 시간도 포함됩니다. 월 예산에 도달하면 대기하고, 예산을 높이면 이어서 실행합니다.</p><p className="muted" style={{marginTop:7}}>달력 기준 사용량 추정이며, 세금·계정의 다른 사용료는 별도입니다. 실제 청구 주기와 금액은 Cloudflare에서 확인하세요.</p><p className="muted" style={{marginTop:7}}>다음 월 시작 {date(state.quota.resetsAt)}</p></>:<><strong>무료 서버 실행량</strong><small>약 {Math.ceil(Math.max(0,state.quota.remaining??((state.quota.budget||540000)-state.quota.used))/60000)}분 남음</small><div className="quota-track"><span style={{width:Math.min(100,state.quota.used/(state.quota.budget||540000)*100)+'%'}}/></div><p className="muted">현재 서버는 무료 요금제로 확인됩니다. 유료 전환 후 아래 버튼을 누르면 하루 9분 제한을 해제하고 대기 중인 확인을 이어갑니다.</p><p className="muted" style={{marginTop:7}}>다음 초기화 {date(state.quota.resetsAt)}</p></>}<button className="full" style={{marginTop:12}} disabled={pending} onClick={async()=>{const r=await act({type:'refreshPlan'});if(r){setError(false);setNotice(r.quota.plan==='paid'?'유료 요금제를 확인했습니다. 하루 9분 제한이 해제됐습니다.':'아직 무료 요금제로 확인됩니다. 유료 전환 뒤 다시 확인해 주세요.');}}}>요금제 적용 다시 확인</button></div></section>
  {settings&&<section className="card"><h2>자동 확인 설정</h2><form onSubmit={async e=>{e.preventDefault();const result=await act({type:'settings',settings},'자동 확인 설정을 저장했습니다.');if(result){dirty.current=false;await refresh();}}}><label className="switch"><span>자동 확인 사용</span><input type="checkbox" checked={settings.dailyEnabled} onChange={e=>edit('dailyEnabled',e.target.checked)} disabled={blocked}/></label><label className="field">확인 간격<select value={settings.checkIntervalMinutes} onChange={e=>edit('checkIntervalMinutes',Number(e.target.value))} disabled={blocked}>{[1,3,6,12,24].map(h=><option value={h*60} key={h}>{h}시간마다</option>)}</select></label><label className="switch"><span>새 글에 좋아요도 누르기</span><input type="checkbox" checked={settings.autoLike} onChange={e=>edit('autoLike',e.target.checked)} disabled={blocked}/></label><label className="field">한 번에 좋아요 최대 개수<input type="number" min={1} max={30} value={settings.maxPerRun} onChange={e=>edit('maxPerRun',Number(e.target.value))} disabled={blocked}/></label><details><summary>반응 계정 설정</summary><label className="field" style={{marginTop:14}}>계정 이름<input value={settings.actorName} onChange={e=>edit('actorName',e.target.value)} disabled={blocked}/></label><label className="field">개인 프로필 주소<input type="url" value={settings.actorUrl} onChange={e=>edit('actorUrl',e.target.value)} disabled={blocked}/></label></details><button className="full primary" style={{marginTop:18}} disabled={blocked}>설정 저장</button><p className="muted" style={{marginTop:14}}>{state.settings.dailyEnabled?'다음 예정 '+date(state.nextRunAt):'현재 자동 확인 꺼짐'}</p></form></section>}</aside></div>}
  <footer className="footer">새 글 도우미 · 개인용 관리 공간<br/>기존 PC 확장 프로그램의 명단과 기록은 자동으로 이전되지 않습니다.</footer>
  {remove&&<div className="modal-shade"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">{remove.name}님을 삭제할까요?</h2><p>확인 대상에서 빠지고 기존 처리 기록은 보관됩니다. ‘삭제한 동료’에서 복원할 수 있습니다.</p><div className="buttons"><button autoFocus onClick={()=>setRemove(null)}>취소</button><button className="danger" onClick={async()=>{const t=remove;setRemove(null);await act({type:'removeTarget',id:t.id},'동료를 삭제했습니다. 필요하면 복원할 수 있습니다.');}}>목록에서 삭제</button></div></section></div>}
  </main>;
}
